### PR TITLE
feat: integrate auth0 for login flow

### PR DESCRIPTION
**Pull request by mohdashraf010897**
**PR Type** `feat`

**Description** The PR migrates the login flow to be handled by Auth0.

https://www.notion.so/reactivesearch/Replace-ACCAPI-login-with-Auth0-b9885f01610f48e59d8230522ebd4f61

---
https://github.com/appbaseio/batteries/pull/313

### CODE REVIEW

**Comment by mohdashraf010897** [comment]
cd src/batteries && git config --global user.email "siddharth@appbase.io" && git config --global user.name "siddharthlatest" && git pull origin master && cd ../../ && yarn build

**Comment by mohdashraf010897** [comment]
Deployed preview - 5 DEC 2022 - 7:45 PM

https://dashboard-abzywzyhh-reactivesearch.vercel.app/

**Comment by deepjyoti30** [comment]
lgtm

**Review by siddharthlatest — APPROVED** [review]
lgtm (y)

**Pull request merged**
