### PR TITLE
Add support for Email Login

### PR DESCRIPTION
**Pull request by jyash97**

### CODE REVIEW

**Comment by metagrover** [comment]
I'm not able to get past the login screen even after adding the received OTP.

**Comment by jyash97** [comment]
Email you used was already registered ?

**Comment by metagrover** [comment]
No, it was a new email.

**Comment by jyash97** [comment]
Yeah that issue has been fixed [here](https://github.com/appbaseio/dashboard/blob/dev/src/utils/index.js#L7).

**Pull request merged**
